from src.backend.bytecode import Opcode, Instruction

def generate_python_source(block: list[Instruction], vm=None) -> str:
    lines = []
    lines.append("def compiled_block(stack, locals_map, globals_map, lookup_var, vm):")
    lines.append("    # Native trace generated by Eigen Trace-Based Adaptive Execution Engine")
    lines.append("    pop = stack.pop")
    lines.append("    append = stack.append")
    
    # Identify and generate LICM (Local Var Hoisting) + Type Guards
    hoist_vars = set()
    if vm is not None:
        loaded_vars = {inst.arg for inst in block if inst.opcode == Opcode.LOAD_VAR}
        stored_vars = {inst.arg for inst in block if inst.opcode == Opcode.STORE_VAR}
        hoist_vars = loaded_vars - stored_vars
        
        for var_name in sorted(hoist_vars):
            clean_name = "".join(c if c.isalnum() else "_" for c in var_name)
            try:
                val = vm.lookup_var(var_name)
                expected_type_name = type(val).__name__
            except Exception:
                expected_type_name = "NoneType"
                
            lines.append(f"    # Hoist and Guard {var_name}")
            lines.append(f"    try:")
            lines.append(f"        var_cache_{clean_name} = lookup_var({repr(var_name)})")
            lines.append(f"    except Exception:")
            lines.append(f"        return True")
            lines.append(f"    if type(var_cache_{clean_name}).__name__ != {repr(expected_type_name)}:")
            lines.append(f"        return True  # Type guard deopt")
            
    for idx, inst in enumerate(block):
        opcode = inst.opcode
        arg = inst.arg
        lines.append(f"    # {inst}")
        
        if opcode == Opcode.LOAD_CONST:
            lines.append(f"    append({repr(arg)})")
            
        elif opcode == Opcode.LOAD_VAR:
            if arg in hoist_vars:
                clean_name = "".join(c if c.isalnum() else "_" for c in arg)
                lines.append(f"    append(var_cache_{clean_name})")
            else:
                lines.append(f"    append(lookup_var({repr(arg)}))")
            
        elif opcode == Opcode.STORE_VAR:
            lines.append(f"    if vm.call_stack:")
            lines.append(f"        vm.call_stack[-1].locals[{repr(arg)}] = pop()")
            lines.append(f"    else:")
            lines.append(f"        globals_map[{repr(arg)}] = pop()")
            
        elif opcode == Opcode.ADD:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a + b)")
            
        elif opcode == Opcode.SUB:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a - b)")
            
        elif opcode == Opcode.MUL:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a * b)")
            
        elif opcode == Opcode.DIV:
            lines.append("    b = pop(); a = pop()")
            lines.append("    if b == 0:")
            lines.append("        vm.throw_exception('DivisionByZeroError: Division by zero.')")
            lines.append("    else:")
            lines.append("        append(a / b)")
            
        elif opcode == Opcode.EQ:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a == b)")
            
        elif opcode == Opcode.NEQ:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a != b)")
            
        elif opcode == Opcode.LT:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a < b)")
            
        elif opcode == Opcode.GT:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a > b)")
            
        elif opcode == Opcode.LTE:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a <= b)")
            
        elif opcode == Opcode.GTE:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(a >= b)")
            
        elif opcode == Opcode.AND:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(bool(a) and bool(b))")
            
        elif opcode == Opcode.OR:
            lines.append("    b = pop(); a = pop()")
            lines.append("    append(bool(a) or bool(b))")
            
        elif opcode == Opcode.NOT:
            lines.append("    a = pop()")
            lines.append("    append(not a)")
            
        elif opcode == Opcode.PRINT:
            lines.append("    print(f'[PRINT DIRECTIVE] {pop()}')")
            
        elif opcode == Opcode.JMP:
            lines.append(f"    vm.ip = {arg}")
            lines.append("    return True")
            
        elif opcode == Opcode.JMP_IF_FALSE:
            lines.append("    cond = pop()")
            lines.append("    if not cond:")
            lines.append(f"        vm.ip = {arg}")
            lines.append("        return True")
            
        elif opcode == Opcode.JMP_IF_TRUE:
            lines.append("    cond = pop()")
            lines.append("    if cond:")
            lines.append(f"        vm.ip = {arg}")
            lines.append("        return True")
            
        elif opcode == Opcode.HALT:
            lines.append("    vm.ip = len(vm.instructions)")
            lines.append("    return True")
            
        elif opcode == Opcode.RET:
            lines.append("    vm.op_ret(None)")
            lines.append("    return True")
            
        elif opcode == Opcode.CALL:
            lines.append(f"    vm.ip = vm.ip + {idx} + 1")
            lines.append(f"    vm.op_call({repr(arg)})")
            lines.append("    return True")
            
        else:
            lines.append(f"    vm.ip = vm.ip + {idx} + 1")
            method_name = f"op_{opcode.lower()}"
            lines.append(f"    if hasattr(vm, '{method_name}'):")
            lines.append(f"        getattr(vm, '{method_name}')({repr(arg)})")
            lines.append("    return True")
            
    lines.append(f"    vm.ip = vm.ip + {len(block)}")
    lines.append("    return False")
    return "\n".join(lines)
